// Register
POST http://localhost:3000/api/register
Content-Type : application/json

{
    "name" : "Wow",
    "username" : "wow",
    "email" : "wow@gmail.com",
    "password" : "wow"
}

###
// Login
POST http://localhost:3000/api/login
Content-Type : application/json

{
    "email" : "wow@gmail.com",
    "password" : "wow"
}

###
// Edit user info
POST http://localhost:3000/api/user/edit-profile
Content-Type : application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZmNkOWJhMzg4MTcxYjcyNjM3ZDYyZCIsImlhdCI6MTY5NDI5MjQyOH0.YRmvDT-PirijeM7_uqUARCcFMu-p3odjB4IgUqWfD6o

{
    "profileImage" : "new-new-profile-image.jpg",
    "coverImage" : "new-cover-image.jpg",
    "nickname" : "New Nickname",
    "major" : "New Major",
    "university" : "New University",
    "location" : "New Location",
    "bio" : "New Bio",
    "skills" : ["Skill 1", "Skill 2"]
}


// get a specific user data
###
GET http://localhost:3000/api/user/wow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjc2NTZmOGM3M2IwNWRmMTM2NTU1OSIsImlhdCI6MTY5NDI1Mzg2OH0.WFrUU8W7Xju1NAlnXE3H0vua4JQ8AxAYLiBeKSvXubU

// search for users and communities
###
GET http://localhost:3000/api/user/search/wow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZmNkOWJhMzg4MTcxYjcyNjM3ZDYyZCIsImlhdCI6MTY5NDI5Njk1NSwiZXhwIjoxNjk0MzAwNTU1fQ.SfbETe8hMv7rDb68lOVsLGkCw6URdO6JcRzSEoDi2-8

// search for users to invite 
###
GET http://localhost:3000/api/user/search/rac/64fc501335e3102409bc028e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjc2NTZmOGM3M2IwNWRmMTM2NTU1OSIsImlhdCI6MTY5NDI1NzM1OX0.-J3gukVTyBcwN0yDSjXXEdY6hGN7StjB3mfgEpDrWBY

// get a specific user friends
###
GET http://localhost:3000/api/user/friends
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjc2NTZmOGM3M2IwNWRmMTM2NTU1OSIsImlhdCI6MTY5NDI1Mzg2OH0.WFrUU8W7Xju1NAlnXE3H0vua4JQ8AxAYLiBeKSvXubU

// create a community
###
POST http://localhost:3000/api/community/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjc2NTZmOGM3M2IwNWRmMTM2NTU1OSIsImlhdCI6MTY5NDI1Mzg2OH0.WFrUU8W7Xju1NAlnXE3H0vua4JQ8AxAYLiBeKSvXubU

{
    "name" : "First Community",
    "description" : "This is the first community",
    "privacy" : "public"
}

// get a community
###
GET http://localhost:3000/api/community/64fc44206036e55f0754642b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjc2NTZmOGM3M2IwNWRmMTM2NTU1OSIsImlhdCI6MTY5NDI1Mzg2OH0.WFrUU8W7Xju1NAlnXE3H0vua4JQ8AxAYLiBeKSvXubU

// delete a community
###
POST http://localhost:3000/api/community/delete/64fc4f9b35e3102409bc0285
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjc2NTZmOGM3M2IwNWRmMTM2NTU1OSIsImlhdCI6MTY5NDI1NTU2M30.KD6XMlPsIlCgJiUjcYz73WUnum8aGvMwKAc4OQsAA20

// update a community
###
POST http://localhost:3000/api/community/update/64fc501335e3102409bc028e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjc2NTZmOGM3M2IwNWRmMTM2NTU1OSIsImlhdCI6MTY5NDI1NzM1OX0.-J3gukVTyBcwN0yDSjXXEdY6hGN7StjB3mfgEpDrWBY

{
    "name" : "First community updated",
    "description" : "First community description updated"
}

// add members to a community
###
POST http://localhost:3000/api/community/64fc501335e3102409bc028e/add-members
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjc2NTZmOGM3M2IwNWRmMTM2NTU1OSIsImlhdCI6MTY5NDI1NzM1OX0.-J3gukVTyBcwN0yDSjXXEdY6hGN7StjB3mfgEpDrWBY

{
    "userIds" : ["64fc602d9b5525054d890830", "64fc602d9b5525054d890830"]
}

// remove members from a community
###
POST http://localhost:3000/api/community/64fc501335e3102409bc028e/remove-members
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjc2NTZmOGM3M2IwNWRmMTM2NTU1OSIsImlhdCI6MTY5NDI1NzM1OX0.-J3gukVTyBcwN0yDSjXXEdY6hGN7StjB3mfgEpDrWBY

{
    "userIds" : ["64ec7987bad32b2defccf98f", "64fc602d9b5525054d890830"]
}



// Friend Requests

// send a friend request
###
POST http://localhost:3000/api/friendship/send-friend-request/64fc602d9b5525054d890830
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWM3OTg3YmFkMzJiMmRlZmNjZjk4ZiIsImlhdCI6MTY5NDI3MjQ2NX0.nUNS5JCvmc9O-WB50kWOc2KjAFoyRCpMuQS-L2y4wwM

// reject a friend request
###
POST http://localhost:3000/api/friendship/reject-friend-request/64ec7987bad32b2defccf98f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZmM2MDJkOWI1NTI1MDU0ZDg5MDgzMCIsImlhdCI6MTY5NDI3NjEwN30.rVXzj3-X84POhTFzbqLQahJ7XZCDt3TqDY6j-IB2-UE

// accept a friend request
###
POST http://localhost:3000/api/friendship/accept-friend-request/64ec7987bad32b2defccf98f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZmM2MDJkOWI1NTI1MDU0ZDg5MDgzMCIsImlhdCI6MTY5NDI3NjEwN30.rVXzj3-X84POhTFzbqLQahJ7XZCDt3TqDY6j-IB2-UE


// Private chat

// create a new private conversation
###
POST http://localhost:3000/api/privateChat/newPrivateConversation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZWM3OTg3YmFkMzJiMmRlZmNjZjk4ZiIsImlhdCI6MTY5NDI3NDY2Nn0.QzPrr30diUcUtC_SJKdGcCUV1I9W4XPfCAUcyLoaW4o

{
    "userOne" : "64fc602d9b5525054d890830",
    "userTwo" : "64ec7987bad32b2defccf98f"
}