export const languagesData = [
    {
        id: 1,
        label: "English"
    }, {
        id: 2,
        label: "Chinese (Mandarin)"
    }, {
        id: 3,
        label: "Spanish"
    }, {
        id: 4,
        label: "Hindi"
    }, {
        id: 5,
        label: "Arabic"
    }, {
        id: 6,
        label: "Bengali"
    }, {
        id: 7,
        label: "Portuguese"
    }, {
        id: 8,
        label: "Russian"
    }, {
        id: 9,
        label: "Japanese"
    }, {
        id: 10,
        label: "French"
    }, {
        id: 11,
        label: "German"
    }, {
        id: 12,
        label: "Korean"
    }, {
        id: 13,
        label: "Turkish"
    }, {
        id: 14,
        label: "Italian"
    }, {
        id: 15,
        label: "Dutch"
    }, {
        id: 16,
        label: "Urdu"
    }, {
        id: 17,
        label: "Polish"
    }, {
        id: 18,
        label: "Vietnamese"
    }, {
        id: 19,
        label: "Thai"
    }, {
        id: 20,
        label: "Persian"
    }, {
        id: 21,
        label: "Romanian"
    }, {
        id: 22,
        label: "Swedish"
    }, {
        id: 23,
        label: "Greek"
    }, {
        id: 24,
        label: "Czech"
    }, {
        id: 25,
        label: "Hungarian"
    }, {
        id: 26,
        label: "Danish"
    }, {
        id: 27,
        label: "Finnish"
    }, {
        id: 28,
        label: "Norwegian"
    }, {
        id: 29,
        label: "Hebrew"
    }, {
        id: 30,
        label: "Malay/Indonesian"
    }
];
